const stylePagina = {
  container: {
    background: "linear-gradient(135deg, #e6ecff, #c9d8f2)",
    minHeight: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
  },
  card: {
    backgroundColor: "#ffffff",
    padding: "40px",
    borderRadius: "12px",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.1)",
    width: "100%",
    maxWidth: "400px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  cartao: {
    backgroundColor: "#ffffff",
    padding: "40px",
    borderRadius: "12px",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.1)",
    width: "100%",
    maxWidth: "400px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  erro: {
    color: "red",
    textAlign: "center",
    marginBottom: "10px",
  },
  input: {
    padding: "12px",
    border: "1px solid #ccd4e0",
    borderRadius: "8px",
    fontSize: "15px",
    outline: "none",
    color: "#1a3e5f",
  },
  botao: {
    padding: "12px",
    background: "linear-gradient(90deg, #1a3e5f, #3d5d8c)",
    color: "#ffffff",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    cursor: "pointer",
    transition: "all 0.3s ease-in-out",
  },
  titulo: {
    textAlign: "center",
    color: "#1a3e5f",
    fontSize: "28px",
    fontWeight: "600",
    marginBottom: "10px",
  },
};

export default stylePagina;
